jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2

      - name: Run the script with API_KEY
        run: |
          echo "API_KEY=$API_KEY"
        env:
          API_KEY: ${{ secrets.API_KEY }}
